# 端口
port 6379
# 绑定所有IP（容器内必须，否则外部无法访问）
bind 0.0.0.0
# 守护进程关闭（容器内前台运行）
daemonize no
# 密码（可自行修改，需与后端config/database.go中一致）
requirepass 123456
# 持久化（RDB+AOF）
save 60 1000
rdbcompression yes
dbfilename dump.rdb
dir /data
appendonly yes
appendfsync everysec
# 超时
timeout 300
protected-mode no
